service: viideon-backend
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: server.handler
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /user
          method: get
      - httpApi:
          path: /user/register
          method: post
      - httpApi:
          path: /user/login
          method: post
      - httpApi:
          path: /user/update/{id}
          method: patch
      - httpApi:
          path: /user/{id}
          method: get
      - httpApi:
          path: /user/verify
          method: post
      - httpApi:
          path: /user/resendVerify
          method: post
      - httpApi:
          path: /user/forgotPassword
          method: post
      - httpApi:
          path: /user/resetPassword
          method: post
      - httpApi:
          path: /user/template
          method: post
      - httpApi:
          path: /user/template
          method: get
      - httpApi:
          path: /user/template/{id}/{userId}
          method: patch
      - httpApi:
          path: /user/preview
          method: post
      - httpApi:
          path: /user/emailvideo
          method: post
      - httpApi:
          path: /video
          method: post
      - httpApi:
          path: /video
          method: get
      - httpApi:
          path: /video
          method: patch
      - httpApi:
          path: /video
          method: delete
      - httpApi:
          path: /video/getTemplate
          method: post
      - httpApi:
          path: /video/email
          method: post
      - httpApi:
          path: /video/updateViews
          method: post
      - httpApi:
          path: /video/updateWatch
          method: post
      - httpApi:
          path: /video/updateEmailShare
          method: post
      - httpApi:
          path: /video/update/cta
          method: post
      - httpApi:
          path: /video/user
          method: get
      - httpApi:
          path: /video/single
          method: get
      - httpApi:
          path: /video/campaignVideos
          method: get
      - httpApi:
          path: /video/multiple/email
          method: post
      - httpApi:
          path: /video/count
          method: get
      - httpApi:
          path: /video/campaign/count
          method: get
      - httpApi:
          path: /video/email/track
          method: get
      - httpApi:
          path: /contact/create
          method: post
      - httpApi:
          path: /email/config
          method: post
      - httpApi:
          path: /email/config
          method: get
      - httpApi:
          path: /email/config
          method: delete
      - httpApi:
          path: /email/send
          method: post
      - httpApi:
          path: /email/send/{id}
          method: post
      - httpApi:
          path: /asset/add
          method: post
      - httpApi:
          path: /asset/addpublicmusic
          method: post
      - httpApi:
          path: /asset/getpublicmusic
          method: get
      - httpApi:
          path: /asset/delpublicmusic/{id}
          method: delete
      - httpApi:
          path: /asset/add/music
          method: post
      - httpApi:
          path: /asset/get
          method: get
      - httpApi:
          path: /asset/getAllAssets
          method: get
      - httpApi:
          path: /asset/get/music
          method: get
      - httpApi:
          path: /asset/remove
          method: delete
      - httpApi:
          path: /asset/remove/music
          method: delete
      - httpApi:
          path: /campaign/templates
          method: get
      - httpApi:
          path: /campaign/templates
          method: post
      - httpApi:
          path: /campaign/templates
          method: patch
      - httpApi:
          path: /campaign/templates/{id}
          method: delete
      - httpApi:
          path: /industry
          method: get
      - httpApi:
          path: /industry
          method: post
      - httpApi:
          path: /industry
          method: patch
      - httpApi:
          path: /industry/{id}
          method: delete
      - httpApi:
          path: /chatvid
          method: post
      - httpApi:
          path: /chatvid
          method: get
      - httpApi:
          path: /chatvid
          method: patch
      - httpApi:
          path: /chatvid
          method: delete
      - httpApi:
          path: /chatvid/reply
          method: post
      - httpApi:
          path: /chatvid/step
          method: patch
      - httpApi:
          path: /chatvid/metrics
          method: post
      - httpApi:
          path: /chatvid/metrics/{id}
          method: post
      - httpApi:
          path: /chatvid/delete/{id}
          method: delete
